---
- hosts: web
  tasks:
    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost'
        insertafter: #<Virtual
        line: <VirtualHost *:8080>
    - name : Change port
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: 'Listen '
        insertafter: 'Listen '
        line: Listen 8080